server:
  port: 8081

spring:
  application:
    name: Api-customer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/practicaBackend?createDatabaseIfNotExist=true
    username: springuser
    password: ThePassword
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka