server:
  port: ${PORT:8888}

spring:
  application:
    name: Config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aquamantop/Esp-Backend
          force-pull: true
          search-paths: configData